HW3 + HW2
DmitryMarchenko/smart-home-2019 pull request #3
Opened 2019-03-21 20:37 UTC by DmitryMarchenko

Переделал 2 домашку и сделал 3

2019-03-23 13:41 UTC, iagoshkov requested changes
все хорошо, только тестов на alarm не заметил. где они?

2019-03-23 13:41 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    private Alarm alarm = new Alarm("ThisIsRightCode", new StdOutNotifier());
Вообще alarm лучше создавать вне дома и передавать в дом через конструктор или через setter

2019-03-23 13:41 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    private Alarm alarm = new Alarm("ThisIsRightCode", new StdOutNotifier());
это называется dependency injection если что

2019-03-23 13:41 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void activate(String code) {
Вот эти три метода работы с alarm не нужно добавлять в дом.
Это нам так на каждый объект внутри дома все его методы в дом добавлять что ли?

2019-03-23 13:50 UTC, DmitryMarchenko commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void activate(String code) {
просто мы же на семинаре обсуждали что делать что-то типо
smartHome.getAlarm().activate(code)
не очень хорошо

2019-03-23 13:51 UTC, DmitryMarchenko commented
> все хорошо, только тестов на alarm не заметил. где они?

забыл про них совсем. можно со следующей дз добавить?

2019-03-27 18:07 UTC, DmitryMarchenko commented
Добавил 4-ое дз.

2019-04-02 20:37 UTC, iagoshkov requested changes
С адаптером немного переделать без наследования.

2019-04-02 20:37 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/adapters/CCSensorEventToSensorEventAdapter.java
> +public class CCSensorEventToSensorEventAdapter extends SensorEvent {
Лучше обойтись без наследования. Сделать просто отдельный класс который на вход принимает CCSensorEvent, а на выходе выдает "старый" SensorEvent.
Так меньше coupling и можно например из одного "нового" события сделать несколько "старых" (если вдруг это понадобится по логике адаптации).

2019-04-02 20:37 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/event/SensorEvent.java
> +        type = SensorEventType.DOOR_CLOSED;
Это вот почему? :)

2019-04-03 17:34 UTC, iagoshkov approved these changes
Ок

2019-04-03 17:34 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/adapters/CCSensorEventToSensorEventAdapter.java
>      public CCSensorEventToSensorEventAdapter(CCSensorEvent ccSensorEvent) {
Можно просто сделать метод convert() который принимает на вход библиотечное событие и возвращает "наше".
Ну ок, так в принципе тоже нормально.

2019-04-03 17:35 UTC, merged